const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));let view='overview',courses=[],signups=[],photos=[],photosError='';
$$('[data-close-modal]').forEach(button=>button.onclick=()=>{const dialog=$('#modal');if(dialog.open)dialog.close('cancel')});
{const style=document.createElement('link');style.rel='stylesheet';style.href='css/brand.css?v=20260827-3';document.head.appendChild(style)}$$('.brand').forEach(brand=>brand.innerHTML='<img class="brand-logo" src="assets/images/logo-cropped.png" alt="賞心學堂 Ink House">');
const titles={overview:'營運總覽',courses:'課程管理',photos:'主頁照片',signups:'報名名單'},audienceName={kids:'兒童班',adult:'成人班'},categoryName={painting:'繪畫',traditional:'傳統藝術',foundation:'基礎',craft:'手作',workshop:'Workshop'};
$('#loginForm').onsubmit=async event=>{event.preventDefault();$('#loginError').textContent='';const data=Object.fromEntries(new FormData(event.target)),button=event.submitter;button.disabled=true;try{await InkData.signIn(data.email,data.password);await showDashboard()}catch(error){$('#loginError').textContent=error.message}finally{button.disabled=false}};
async function loadData(){[courses,signups]=await Promise.all([InkData.courses(true),InkData.signups()]);try{photos=await InkData.sitePhotos();photosError=''}catch(error){photos=[];photosError=error.message}}
async function showDashboard(){$('#loginScreen').hidden=true;$('#dashboard').hidden=false;try{await loadData();render()}catch(error){InkData.signOut();$('#dashboard').hidden=true;$('#loginScreen').hidden=false;$('#loginError').textContent=`無法讀取後台資料：${error.message}`}}
InkData.ready.then(()=>{if(InkData.isSignedIn())showDashboard()}).catch(error=>$('#loginError').textContent=error.message);$('#logout').onclick=()=>{InkData.signOut();location.reload()};
$$('aside nav button').forEach(button=>button.onclick=()=>{$$('aside nav button').forEach(x=>x.classList.remove('active'));button.classList.add('active');view=button.dataset.view;render()});
function render(){$('#viewTitle').textContent=titles[view];if(view==='overview')$('#content').innerHTML=`<div class="stats"><div class="stat"><span>全部課程</span><strong>${courses.length}</strong></div><div class="stat"><span>兒童／成人</span><strong>${courses.filter(c=>c.audience==='kids').length} / ${courses.filter(c=>c.audience==='adult').length}</strong></div><div class="stat"><span>學生報名</span><strong>${signups.length}</strong></div></div><div class="panel"><div class="panel-head"><h2>最新報名</h2></div>${signupTable(signups.slice(0,5))}</div>`;if(view==='courses')$('#content').innerHTML=`<div class="panel"><div class="panel-head"><h2>所有課程</h2><button class="add-button" onclick="openCourse()">＋ 新增課程</button></div><table><thead><tr><th>課程</th><th>對象</th><th>類別</th><th>時間／費用</th><th>狀態</th><th>操作</th></tr></thead><tbody>${courses.map(c=>`<tr><td><strong>${esc(c.name)}</strong><br><small>${esc(c.label)}</small></td><td><span class="badge">${audienceName[c.audience]}</span></td><td>${categoryName[c.category]||c.category}</td><td>${esc(c.duration)}<br>${esc(c.price)}</td><td>${c.published?'已發布':'草稿'}</td><td class="actions"><button onclick="openCourse('${c.id}')">編輯</button><button class="delete" onclick="removeItem('${c.id}')">刪除</button></td></tr>`).join('')}</tbody></table></div>`;if(view==='signups')$('#content').innerHTML=`<div class="panel"><div class="panel-head"><h2>學生報名資料</h2></div>${signupTable(signups)}</div>`;if(view==='photos')renderPhotos()}
function signupTable(list){return list.length?`<table><thead><tr><th>學員</th><th>聯絡</th><th>報名課程</th><th>偏好時間</th><th>報名日期</th><th>狀態</th><th>操作</th></tr></thead><tbody>${list.map(s=>{const ids=s.course_ids?.length?s.course_ids:[s.course_id],names=ids.map(id=>courses.find(c=>c.id===id)?.name).filter(Boolean);return `<tr><td><strong>${esc(s.student_name)}</strong><br>年齡：${esc(s.student_age||'—')}</td><td>${esc(s.phone||'')}<br>微信：${esc(s.wechat||'—')}</td><td>${names.map(esc).join('<br>')||'—'}</td><td>${esc(s.preferred_time||'現有時間可以')}</td><td>${new Date(s.created_at).toLocaleString('zh-HK')}</td><td><span class="badge">${esc(s.status)}</span></td><td class="actions"><button class="delete" onclick="removeSignup('${s.id}')">刪除</button></td></tr>`}).join('')}</tbody></table>`:'<div class="empty">目前還沒有報名資料</div>'}
function editor(title,html,save){$('#modalTitle').textContent=title;$('#formFields').innerHTML=html;const dialog=$('#modal');dialog.showModal();$('#editorForm').onsubmit=async event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();event.submitter.disabled=true;try{const formData=new FormData(event.target),data=Object.fromEntries(formData);data.weekdays=formData.getAll('weekdays');await save(data);dialog.close();await loadData();render()}catch(error){alert(`儲存失敗：${error.message}`)}finally{event.submitter.disabled=false}}}
window.removeItem=async(id)=>{if(!confirm('確定要刪除這筆資料嗎？'))return;try{await InkData.deleteCourse(id);await loadData();render()}catch(error){alert(`刪除失敗：${error.message}`)}};
window.removeSignup=async(id)=>{if(!confirm('確定要刪除這筆報名嗎？'))return;try{await InkData.deleteSignup(id);await loadData();render()}catch(error){alert(`刪除失敗：${error.message}`)}};
window.openCourse=id=>{const c=courses.find(x=>x.id===id)||{},days=['日','一','二','三','四','五','六'];editor(id?'編輯課程':'新增課程',`<label>課程名稱<input name="name" required value="${esc(c.name)}"></label><label>課程對象<select name="audience"><option value="kids">兒童班</option><option value="adult">成人班</option></select></label><label>課程類別<input name="category" required placeholder="例如：水彩、素描、啟蒙班" value="${esc(c.category)}"></label><label>價錢 MOP<input type="number" name="priceMop" min="0" value="${c.priceMop??''}"></label><div class="admin-form-row"><label>課程開始日期<input type="date" name="startDate" required value="${esc(c.startDate)}"></label><label>課程結束日期<input type="date" name="endDate" required value="${esc(c.endDate)}"></label></div><fieldset class="weekday-field"><legend>逢星期幾（可多選）</legend>${days.map((day,index)=>`<label><input type="checkbox" name="weekdays" value="${index}" ${c.weekdays?.includes(index)?'checked':''}> 星期${day}</label>`).join('')}</fieldset><div class="admin-form-row"><label>上課開始時間<input type="time" name="startTime" required value="${esc(c.startTime)}"></label><label>上課結束時間<input type="time" name="endTime" required value="${esc(c.endTime)}"></label></div><label>上課老師<input name="teacher" required value="${esc(c.teacher)}"></label><label>課程簡介<textarea name="desc" required>${esc(c.desc)}</textarea></label><label>課程圖片<input type="file" name="imageFile" accept="image/jpeg,image/png,image/webp,image/gif"><small>JPG、PNG、WebP 或 GIF，最多 5MB</small>${c.imageUrl?`<img src="${esc(c.imageUrl)}" alt="目前課程圖片" style="display:block;width:100%;max-height:220px;object-fit:cover;margin-top:10px">`:''}</label>`,async data=>{if(!data.weekdays.length)throw new Error('請至少選擇一個上課星期');const file=data.imageFile;let imageUrl=c.imageUrl||'';if(file instanceof File&&file.size>0)imageUrl=await InkData.uploadCourseImage(file,c.slug||'course');await InkData.saveCourse({...data,id:c.id,slug:c.slug,color:c.color,icon:c.icon,imageUrl})});if(c.audience)$('[name=audience]').value=c.audience;const fileInput=$('[name=imageFile]');fileInput.onchange=()=>{const old=$('#newImagePreview');old?.remove();if(fileInput.files[0]){const image=document.createElement('img');image.id='newImagePreview';image.src=URL.createObjectURL(fileInput.files[0]);image.style='display:block;width:100%;max-height:220px;object-fit:cover;margin-top:10px';fileInput.parentElement.appendChild(image)}}};

function slideshowPhotos(){return photos.filter(p=>p.placement==='slideshow').sort((a,b)=>a.sortOrder-b.sortOrder)}
function photoCard(photo,actions,empty){return `<div class="photo-card">${photo?.imageUrl?`<img src="${esc(photo.imageUrl)}" alt="">`:`<div class="photo-empty">${empty}</div>`}<div class="actions">${actions}</div></div>`}
function bindImagePreview(){const fileInput=$('[name=imageFile]');if(!fileInput)return;fileInput.onchange=()=>{const old=$('#newImagePreview');old?.remove();if(fileInput.files[0]){const image=document.createElement('img');image.id='newImagePreview';image.src=URL.createObjectURL(fileInput.files[0]);image.style='display:block;width:100%;max-height:220px;object-fit:cover;margin-top:10px';fileInput.parentElement.appendChild(image)}}}
function renderPhotos(){
  if(photosError){$('#content').innerHTML=`<div class="panel"><p>無法載入主頁照片。請先在 Supabase SQL Editor 執行 <code>supabase/site-photos.sql</code>。</p><p class="empty">${esc(photosError)}</p></div>`;return}
  const slides=slideshowPhotos(),large=photos.find(p=>p.placement==='about-large'),small=photos.find(p=>p.placement==='about-small');
  $('#content').innerHTML=`<div class="panel"><div class="panel-head"><h2>輪播照片</h2><button class="add-button" onclick="openSlideshowPhoto()">＋ 新增輪播照片</button></div>${slides.length?`<div class="photo-grid">${slides.map((p,i)=>photoCard(p,`<button onclick="movePhoto('${p.id}',-1)" ${i===0?'disabled':''}>上移</button><button onclick="movePhoto('${p.id}',1)" ${i===slides.length-1?'disabled':''}>下移</button><button class="delete" onclick="removePhoto('${p.id}')">刪除</button>`)).join('')}</div>`:'<div class="empty">尚未上傳輪播照片，主頁會繼續顯示目前的預設畫面</div>'}</div><div class="panel"><div class="panel-head"><h2>歡迎區塊照片</h2></div><div class="about-slots"><div><p class="slot-label">大圖 · 學堂空間</p>${photoCard(large,`<button onclick="openAboutPhoto('about-large')">${large?'更換照片':'上傳照片'}</button>${large?`<button class="delete" onclick="removePhoto('${large.id}')">移除</button>`:''}`,'尚未上傳')}</div><div><p class="slot-label">小圖 · 創作過程</p>${photoCard(small,`<button onclick="openAboutPhoto('about-small')">${small?'更換照片':'上傳照片'}</button>${small?`<button class="delete" onclick="removePhoto('${small.id}')">移除</button>`:''}`,'尚未上傳')}</div></div></div>`
}
window.openSlideshowPhoto=()=>{editor('新增輪播照片',`<label>照片<input type="file" name="imageFile" accept="image/jpeg,image/png,image/webp,image/gif" required><small>JPG、PNG、WebP 或 GIF，最多 5MB</small></label><label>說明文字（選填）<input name="alt" placeholder="例如：課堂創作"></label>`,async data=>{const file=data.imageFile;if(!(file instanceof File)||!file.size)throw new Error('請選擇照片');const imageUrl=await InkData.uploadCourseImage(file,'homepage');const slides=slideshowPhotos();await InkData.saveSitePhoto({placement:'slideshow',imageUrl,alt:data.alt||'',sortOrder:slides.length?Math.max(...slides.map(p=>p.sortOrder))+10:0})});bindImagePreview()};
window.openAboutPhoto=placement=>{const photo=photos.find(p=>p.placement===placement)||{},title=placement==='about-large'?'學堂空間照片':'創作過程照片';editor(photo.id?`更換${title}`:`上傳${title}`,`<label>照片<input type="file" name="imageFile" accept="image/jpeg,image/png,image/webp,image/gif" ${photo.imageUrl?'':'required'}><small>JPG、PNG、WebP 或 GIF，最多 5MB</small>${photo.imageUrl?`<img src="${esc(photo.imageUrl)}" alt="目前照片" style="display:block;width:100%;max-height:220px;object-fit:cover;margin-top:10px">`:''}</label><label>說明文字（選填）<input name="alt" value="${esc(photo.alt)}"></label>`,async data=>{const file=data.imageFile;let imageUrl=photo.imageUrl||'';if(file instanceof File&&file.size>0)imageUrl=await InkData.uploadCourseImage(file,'homepage');if(!imageUrl)throw new Error('請選擇照片');await InkData.saveSitePhoto({id:photo.id,placement,imageUrl,alt:data.alt||'',sortOrder:photo.sortOrder||0})});bindImagePreview()};
window.movePhoto=async(id,dir)=>{const slides=slideshowPhotos();const index=slides.findIndex(p=>p.id===id),next=index+dir;if(index<0||next<0||next>=slides.length)return;try{await Promise.all([InkData.saveSitePhoto({...slides[index],sortOrder:slides[next].sortOrder}),InkData.saveSitePhoto({...slides[next],sortOrder:slides[index].sortOrder})]);await loadData();render()}catch(error){alert(`排序失敗：${error.message}`)}};
window.removePhoto=async id=>{if(!confirm('確定要移除這張照片嗎？'))return;try{await InkData.deleteSitePhoto(id);await loadData();render()}catch(error){alert(`刪除失敗：${error.message}`)}};
