(function(){
const loadConfig=()=>new Promise((resolve,reject)=>{if(window.SUPABASE_CONFIG)return resolve();const script=document.createElement('script');script.src='supabase/config.js';script.onload=resolve;script.onerror=()=>reject(new Error('無法載入 Supabase 設定'));document.head.appendChild(script)});
let config,token=sessionStorage.getItem('ink_supabase_token')||'';
async function request(path,{method='GET',body,auth=false,prefer}={}){await ready;const headers={apikey:config.anonKey,'Content-Type':'application/json',Authorization:`Bearer ${auth&&token?token:config.anonKey}`};if(prefer)headers.Prefer=prefer;const response=await fetch(`${config.url}${path}`,{method,headers,body:body?JSON.stringify(body):undefined});if(!response.ok){let message=`Supabase ${response.status}`;try{const error=await response.json();message=error.message||error.msg||error.error_description||message}catch{}throw new Error(message)}if(response.status===204)return null;const text=await response.text();return text?JSON.parse(text):null}
const courseTimeSummary=row=>{const names=['日','一','二','三','四','五','六'],days=(row.weekdays||[]).map(day=>`星期${names[day]}`).join('、'),start=(row.class_start_time||'').slice(0,5),end=(row.class_end_time||'').slice(0,5);return row.course_start_date&&row.course_end_date&&days?`${row.teacher||'老師待定'} · ${row.course_start_date} 至 ${row.course_end_date} · ${days} ${start}–${end}`:'時間待定'};
const mapCourse=row=>({id:row.id,slug:row.slug,name:row.name,label:row.english_name||'',audience:row.audience,category:row.category,age:row.age_range||'',level:row.level||'',duration:courseTimeSummary(row),durationMinutes:row.duration_minutes,price:row.price_mop==null?'詳情請查詢':`MOP ${Number(row.price_mop).toLocaleString('en-US')}`,priceMop:row.price_mop,teacher:row.teacher||'',startDate:row.course_start_date||'',endDate:row.course_end_date||'',weekdays:row.weekdays||[],startTime:(row.class_start_time||'').slice(0,5),endTime:(row.class_end_time||'').slice(0,5),desc:row.description||'',learn:row.learning_points||[],color:row.color||'#c5dcae',icon:row.icon||'藝',featured:row.featured,published:row.published,sortOrder:row.sort_order||0,imageUrl:row.image_url||''});
const mapSession=row=>({id:row.id,courseId:row.course_id,teacher:row.teacher||'導師待定',startsAt:row.starts_at,endsAt:row.ends_at,capacity:row.capacity,spots:row.available_spots,status:row.status,notes:row.notes||''});
const mapSitePhoto=row=>({id:row.id,placement:row.placement,imageUrl:row.image_url,alt:row.alt_text||'',sortOrder:row.sort_order||0});
const ready=loadConfig().then(()=>{config=window.SUPABASE_CONFIG;if(!config?.url||!config?.anonKey)throw new Error('Supabase 設定不完整')});
window.InkData={
ready,
async courses(includeDrafts=false){const query=includeDrafts?'':'&published=eq.true';const rows=await request(`/rest/v1/courses?select=*&order=sort_order.asc${query}`,{auth:includeDrafts});return rows.map(mapCourse)},
async schedule(includeAll=false){const query=includeAll?'':'&status=in.(open,full)';const rows=await request(`/rest/v1/class_sessions?select=*&order=starts_at.asc${query}`,{auth:includeAll});return rows.map(mapSession)},
async sitePhotos(){const rows=await request('/rest/v1/site_photos?select=*&order=sort_order.asc');return rows.map(mapSitePhoto)},
async signups(){return request('/rest/v1/registrations?select=*&order=created_at.desc',{auth:true})},
async submitRegistration(data){const courseIds=data.courseIds||[];const payload={course_id:courseIds[0],course_ids:courseIds,class_session_id:data.scheduleId||null,student_name:data.name,student_age:data.age||null,phone:data.phone,wechat:data.wechat||null,preferred_time:data.preferredTime||null,status:'new',source:'website'};return request('/rest/v1/registrations',{method:'POST',body:payload,prefer:'return=minimal'})},
async signIn(email,password){await ready;const response=await fetch(`${config.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:config.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)throw new Error(data.error_description||data.msg||'登入失敗');token=data.access_token;sessionStorage.setItem('ink_supabase_token',token);sessionStorage.setItem('ink_supabase_refresh',data.refresh_token||'');return data.user},
signOut(){token='';sessionStorage.removeItem('ink_supabase_token');sessionStorage.removeItem('ink_supabase_refresh')},
isSignedIn(){return Boolean(token)},
async saveCourse(course){const payload={slug:course.slug||course.id||crypto.randomUUID(),name:course.name,audience:course.audience,category:course.category,price_mop:course.priceMop===''?null:Number(course.priceMop),teacher:course.teacher||null,course_start_date:course.startDate||null,course_end_date:course.endDate||null,weekdays:(course.weekdays||[]).map(Number),class_start_time:course.startTime||null,class_end_time:course.endTime||null,description:course.desc||'',image_url:course.imageUrl||null,color:course.color||'#c5dcae',icon:course.icon||'藝',featured:false,published:true,sort_order:Number(course.sortOrder)||0};return course.id?request(`/rest/v1/courses?id=eq.${course.id}`,{method:'PATCH',body:payload,auth:true,prefer:'return=minimal'}):request('/rest/v1/courses',{method:'POST',body:payload,auth:true,prefer:'return=minimal'})},
async uploadCourseImage(file,slug='course'){await ready;if(!token)throw new Error('請先登入後台');if(!file?.type?.startsWith('image/'))throw new Error('請選擇圖片檔案');if(file.size>5*1024*1024)throw new Error('圖片不可超過 5MB');const extension=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const safeSlug=String(slug).toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-');const path=`${safeSlug}/${Date.now()}-${crypto.randomUUID()}.${extension}`;const response=await fetch(`${config.url}/storage/v1/object/course-images/${path}`,{method:'POST',headers:{apikey:config.anonKey,Authorization:`Bearer ${token}`,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.message||error.error||'圖片上傳失敗')}return `${config.url}/storage/v1/object/public/course-images/${path}`},
async deleteCourse(id){return request(`/rest/v1/courses?id=eq.${id}`,{method:'DELETE',auth:true})},
async deleteSignup(id){return request(`/rest/v1/registrations?id=eq.${id}`,{method:'DELETE',auth:true})},
async saveSitePhoto(photo){const payload={placement:photo.placement,image_url:photo.imageUrl,alt_text:photo.alt||'',sort_order:Number(photo.sortOrder)||0};return photo.id?request(`/rest/v1/site_photos?id=eq.${photo.id}`,{method:'PATCH',body:payload,auth:true,prefer:'return=minimal'}):request('/rest/v1/site_photos',{method:'POST',body:payload,auth:true,prefer:'return=minimal'})},
async deleteSitePhoto(id){return request(`/rest/v1/site_photos?id=eq.${id}`,{method:'DELETE',auth:true})}
};
})();
