(function(){
	const loadConfig=()=>new Promise((resolve,reject)=>{if(window.SUPABASE_CONFIG)return resolve();const script=document.createElement('script');script.src='supabase/config.js';script.onload=resolve;script.onerror=()=>reject(new Error('無法載入 Supabase 設定'));document.head.appendChild(script)});
	let config,token=sessionStorage.getItem('ink_supabase_token')||'';
	async function request(path,{method='GET',body,auth=false,prefer}={}){await ready;const headers={apikey:config.anonKey,'Content-Type':'application/json',Authorization:`Bearer ${auth&&token?token:config.anonKey}`};if(prefer)headers.Prefer=prefer;const response=await fetch(`${config.url}${path}`,{method,headers,body:body?JSON.stringify(body):undefined});if(!response.ok){let message=`Supabase ${response.status}`;try{const error=await response.json();message=error.message||error.msg||error.error_description||message}catch{}throw new Error(message)}if(response.status===204)return null;const text=await response.text();return text?JSON.parse(text):null}
	const weekdayNames=['日','一','二','三','四','五','六'];
	const isoDay=iso=>new Date(`${String(iso).slice(0,10)}T00:00:00`).getDay();
	const money=n=>`MOP ${Number(n).toLocaleString('en-US')}`;
	const formatSessionDates=dates=>{const parts=(dates||[]).map(iso=>String(iso).slice(0,10).split('-'));if(!parts.length)return '';const years=new Set(parts.map(part=>part[0]));return parts.map(([year,month,day])=>years.size>1?`${Number(day)}/${Number(month)}/${year}`:`${Number(day)}/${Number(month)}`).join('、')};
	const formatWeekly=row=>{const slots=[...(row.weekly_slots||[])];if(!slots.length&&Array.isArray(row.tracks))row.tracks.forEach(track=>(track.slots||[]).forEach(slot=>slots.push(slot)));if(!slots.length)return '';const days=[...new Set(slots.map(slot=>slot.weekday))].sort();return `逢${days.map(day=>`星期${weekdayNames[day]}`).join('、')}`};
	const courseTimeSummary=row=>{const weekly=formatWeekly(row);if(weekly)return `${row.teacher||'老師待定'} · ${weekly}`;const start=(row.class_start_time||'').slice(0,5),end=(row.class_end_time||'').slice(0,5),time=start&&end?`${start}–${end}`:'',dates=row.session_dates||[];if(dates.length){const days=[...new Set(dates.map(isoDay))].sort();const dayText=days.length?`（逢${days.map(day=>`星期${weekdayNames[day]}`).join('、')}）`:'';return `${row.teacher||'老師待定'} · ${formatSessionDates(dates)}${dayText}${time?' '+time:''}`}const days=(row.weekdays||[]).map(day=>`星期${weekdayNames[day]}`).join('、');return row.course_start_date&&row.course_end_date&&days?`${row.teacher||'老師待定'} · ${row.course_start_date} 至 ${row.course_end_date} · ${days} ${start}–${end}`:'時間待定'};
	const courseFeeText=row=>{if(row.audience==='adult'){const parts=[];if(row.tuition_mop!=null)parts.push(`學費 ${money(row.tuition_mop)}${row.hold_edu?'（可用持教）':''}`);if(row.price_mop!=null)parts.push(`材料費 ${money(row.price_mop)}（需自費）`);return parts.join(' + ')||'詳情請查詢'}return row.price_mop==null?'詳情請查詢':`試堂費 ${money(row.price_mop)}`};
	const mapCourse=row=>({id:row.id,slug:row.slug,name:row.name,label:row.english_name||'',audience:row.audience,category:row.category,age:row.age_range||'',level:row.level||'',className:row.class_name||'',sessionDates:(row.session_dates||[]).map(date=>String(date).slice(0,10)),tuitionMop:row.tuition_mop??null,holdEdu:Boolean(row.hold_edu),duration:courseTimeSummary(row),durationMinutes:row.duration_minutes,price:row.price_mop==null?'詳情請查詢':money(row.price_mop),priceMop:row.price_mop,feeText:courseFeeText(row),teacher:row.teacher||'',startDate:row.course_start_date||'',endDate:row.course_end_date||'',weekdays:row.weekdays||[],startTime:(row.class_start_time||'').slice(0,5),endTime:(row.class_end_time||'').slice(0,5),desc:row.description||'',learn:row.learning_points||[],focus:row.focus_points||[],tracks:Array.isArray(row.tracks)?row.tracks:[],weeklySlots:Array.isArray(row.weekly_slots)?row.weekly_slots:[],color:row.color||'#c5dcae',icon:row.icon||'藝',featured:row.featured,published:row.published,sortOrder:row.sort_order||0,imageUrl:row.image_url||'',capacity:row.capacity??null,enrolledCount:row.enrolled_count||0,teacherWorks:row.teacher_works||[],studentWorks:row.student_works||[],otherWorks:row.other_works||[],isFull:row.capacity!=null&&(row.enrolled_count||0)>=row.capacity,feeLabel:row.audience==='kids'?'試堂費':'材料費'});
	const mapSession=row=>({id:row.id,courseId:row.course_id,teacher:row.teacher||'導師待定',startsAt:row.starts_at,endsAt:row.ends_at,capacity:row.capacity,spots:row.available_spots,status:row.status,notes:row.notes||''});
	const mapSitePhoto=row=>({id:row.id,placement:row.placement,imageUrl:row.image_url,alt:row.alt_text||'',sortOrder:row.sort_order||0});
	const ready=loadConfig().then(()=>{config=window.SUPABASE_CONFIG;if(!config?.url||!config?.anonKey)throw new Error('Supabase 設定不完整')});
	let syncTimer=null;
	function queueGithubSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>{window.InkData.triggerImageSync().catch(error=>console.warn('GitHub 圖片同步失敗',error))},2500)}
	async function processImage(file,opts={}){
		  if(!file?.type?.startsWith('image/'))throw new Error('請選擇圖片檔案');
		  if(file.size>20*1024*1024)throw new Error('圖片不可超過 20MB');
		  if(file.type==='image/gif')return file;
		  let bitmap;
		  try{bitmap=await createImageBitmap(file,{imageOrientation:'from-image'})}catch{return file}
		  const maxEdge=1600,maxRatio=4/3;
		  let sx=0,sy=0,sw=bitmap.width,sh=bitmap.height;
		  if(opts.crop!==false){
		    if(sw/sh>maxRatio){sx=(sw-sh*maxRatio)/2;sw=sh*maxRatio}
		    else if(sh/sw>maxRatio){sy=(sh-sw*maxRatio)/2;sh=sw*maxRatio}
		  }
		  const scale=Math.min(1,maxEdge/Math.max(sw,sh));
		  const width=Math.max(1,Math.round(sw*scale)),height=Math.max(1,Math.round(sh*scale));
		  const canvas=document.createElement('canvas');
		  canvas.width=width;canvas.height=height;
		  const ctx=canvas.getContext('2d',{alpha:false});
		  ctx.fillStyle='#fff';ctx.fillRect(0,0,width,height);
		  ctx.drawImage(bitmap,sx,sy,sw,sh,0,0,width,height);
		  bitmap.close?.();
		  let quality=0.82,blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));
		  while(blob&&blob.size>900*1024&&quality>0.5){quality-=0.08;blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality))}
		  if(!blob)return file;
		  return new File([blob],`${(file.name.replace(/\.[^.]+$/,'')||'image')}.jpg`,{type:'image/jpeg'});
		}
		document.addEventListener('error',event=>{const img=event.target;if(img&&img.tagName==='IMG'&&img.dataset.cloud&&img.src!==img.dataset.cloud){img.src=img.dataset.cloud}},true);
	window.InkData={
	ready,
	async courses(includeDrafts=false){const query=includeDrafts?'':'&published=eq.true';const rows=await request(`/rest/v1/courses?select=*&order=sort_order.asc${query}`,{auth:includeDrafts});return rows.map(mapCourse)},
	async schedule(includeAll=false){const query=includeAll?'':'&status=in.(open,full)';const rows=await request(`/rest/v1/class_sessions?select=*&order=starts_at.asc${query}`,{auth:includeAll});return rows.map(mapSession)},
	async sitePhotos(){const rows=await request('/rest/v1/site_photos?select=*&order=sort_order.asc');return rows.map(mapSitePhoto)},
	async signups(){return request('/rest/v1/registrations?select=*&order=created_at.desc',{auth:true})},
	async submitRegistration(data){const courseIds=data.courseIds||[];const payload={course_id:courseIds[0],course_ids:courseIds,class_session_id:data.scheduleId||null,student_name:data.name,student_age:data.age||null,phone:data.phone,wechat:data.wechat||null,preferred_time:data.preferredTime||data.selectedTime||null,selected_time:data.selectedTime||null,fee_type:data.feeType||null,fee_mop:data.feeMop==null||data.feeMop===''?null:Number(data.feeMop),status:'new',source:'website'};try{return await request('/rest/v1/registrations',{method:'POST',body:payload,prefer:'return=minimal'})}catch(error){delete payload.selected_time;delete payload.fee_type;delete payload.fee_mop;return request('/rest/v1/registrations',{method:'POST',body:payload,prefer:'return=minimal'})}},
	async signIn(email,password){await ready;const response=await fetch(`${config.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:config.anonKey,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)throw new Error(data.error_description||data.msg||'登入失敗');token=data.access_token;sessionStorage.setItem('ink_supabase_token',token);sessionStorage.setItem('ink_supabase_refresh',data.refresh_token||'');return data.user},
	signOut(){token='';sessionStorage.removeItem('ink_supabase_token');sessionStorage.removeItem('ink_supabase_refresh')},
	isSignedIn(){return Boolean(token)},
		imgTag(url,alt='',extra=''){const raw=String(url||'');const pos=raw.match(/#pos=(\d+),(\d+)/);const yOnly=raw.match(/#y=(\d+)/);const x=pos?pos[1]:'50';const y=pos?pos[2]:(yOnly?yOnly[1]:'50');const cloud=raw.replace(/#.*$/,'');const match=cloud.match(/\/storage\/v1\/object\/public\/course-images\/(.+)$/);const src=match?`assets/images/uploads/${match[1]}`:cloud;const attr=value=>String(value||'').replace(/"/g,'&quot;');const posAttr=(!/\bstyle=/.test(extra)&&(x!=='50'||y!=='50'))?` style="object-position:${x}% ${y}%"`:'';return `<img src="${attr(src)}" alt="${attr(alt)}"${match?` data-cloud="${attr(cloud)}"`:''}${posAttr} ${extra}>`},
		async triggerImageSync(){if(!token)return;let rows=[];try{rows=await request('/rest/v1/site_settings?key=in.(github_token,github_repo)',{auth:true})}catch(error){console.warn('讀取 GitHub 同步設定失敗',error);return}const map=Object.fromEntries((rows||[]).map(row=>[row.key,row.value]));const gh=map.github_token||'';const repo=map.github_repo||'marcosouza216/ink-house';if(!gh||gh.length<20){console.warn('尚未設定 github_token，圖片不會自動同步到 GitHub');return}const response=await fetch(`https://api.github.com/repos/${repo}/dispatches`,{method:'POST',headers:{Authorization:`Bearer ${gh}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'},body:JSON.stringify({event_type:'sync-images'})});if(!response.ok&&response.status!==204)throw new Error(`無法觸發 GitHub 同步（HTTP ${response.status}）`)},
		async uploadCourseImage(file,slug='course',opts={}){await ready;if(!token)throw new Error('請先登入後台');file=await processImage(file,opts);const extension=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const safeSlug=String(slug).toLowerCase().replace(/[^a-z0-9-]/g,'-').replace(/-+/g,'-')||'course';const filename=`${Date.now()}-${crypto.randomUUID()}.${extension}`;const path=`${safeSlug}/${filename}`;const response=await fetch(`${config.url}/storage/v1/object/course-images/${path}`,{method:'POST',headers:{apikey:config.anonKey,Authorization:`Bearer ${token}`,'Content-Type':file.type,'x-upsert':'false'},body:file});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.message||error.error||'圖片上傳失敗')}const cloudUrl=`${config.url}/storage/v1/object/public/course-images/${path}`;queueGithubSync();return cloudUrl},
async saveCourse(course){const dates=[...new Set((course.sessionDates||[]).map(date=>String(date).slice(0,10)).filter(Boolean))].sort();const weeklySlots=(course.weeklySlots||[]).map(slot=>({weekday:Number(slot.weekday),start:String(slot.start||'').slice(0,5),end:String(slot.end||'').slice(0,5),...(slot.label?{label:String(slot.label)}:{}),...(slot.trackId?{trackId:slot.trackId}:{})})).filter(slot=>slot.start&&slot.end);const weekdays=weeklySlots.length?[...new Set(weeklySlots.map(slot=>slot.weekday))].sort():[...new Set(dates.map(isoDay))].sort();const payload={slug:course.slug||course.id||crypto.randomUUID(),name:course.name,audience:course.audience,category:course.category,class_name:course.className||null,price_mop:course.priceMop===''||course.priceMop==null?null:Number(course.priceMop),tuition_mop:course.audience==='adult'&&course.tuitionMop!==''&&course.tuitionMop!=null?Number(course.tuitionMop):null,hold_edu:course.audience==='adult'&&Boolean(course.holdEdu),teacher:course.teacher||null,session_dates:dates,weekly_slots:weeklySlots,tracks:course.tracks||[],course_start_date:dates[0]||course.startDate||null,course_end_date:dates[dates.length-1]||course.endDate||null,weekdays,class_start_time:course.startTime||weeklySlots[0]?.start||null,class_end_time:course.endTime||weeklySlots[0]?.end||null,description:course.desc||'',age_range:course.age||null,level:course.level||null,english_name:course.label||null,learning_points:course.learn||[],focus_points:course.focus||[],image_url:course.imageUrl||null,color:course.color||'#c5dcae',icon:course.icon||'藝',featured:false,published:true,sort_order:Number(course.sortOrder)||0,capacity:course.capacity===''||course.capacity==null?null:Number(course.capacity),teacher_works:course.teacherWorks||[],student_works:course.studentWorks||[],other_works:course.otherWorks||[]};const send=body=>course.id?request(`/rest/v1/courses?id=eq.${course.id}`,{method:'PATCH',body,auth:true,prefer:'return=minimal'}):request('/rest/v1/courses',{method:'POST',body,auth:true,prefer:'return=minimal'});try{return await send(payload)}catch(error){delete payload.other_works;try{return await send(payload)}catch{delete payload.capacity;delete payload.teacher_works;delete payload.student_works;try{return await send(payload)}catch{delete payload.class_name;delete payload.session_dates;delete payload.tuition_mop;delete payload.hold_edu;delete payload.focus_points;delete payload.weekly_slots;delete payload.tracks;return send(payload)}}}},
	async deleteCourse(id){await request(`/rest/v1/registrations?course_id=eq.${id}`,{method:'DELETE',auth:true});try{await request(`/rest/v1/registrations?course_ids=cs.{${id}}`,{method:'DELETE',auth:true})}catch{}return request(`/rest/v1/courses?id=eq.${id}`,{method:'DELETE',auth:true})},
	async deleteSignup(id){return request(`/rest/v1/registrations?id=eq.${id}`,{method:'DELETE',auth:true})},
	async saveSitePhoto(photo){const payload={placement:photo.placement,image_url:photo.imageUrl,alt_text:photo.alt||'',sort_order:Number(photo.sortOrder)||0};return photo.id?request(`/rest/v1/site_photos?id=eq.${photo.id}`,{method:'PATCH',body:payload,auth:true,prefer:'return=minimal'}):request('/rest/v1/site_photos',{method:'POST',body:payload,auth:true,prefer:'return=minimal'})},
	async deleteSitePhoto(id){return request(`/rest/v1/site_photos?id=eq.${id}`,{method:'DELETE',auth:true})}
	};
	})();
